// File: src/dataSoal.js

export const questionsData = [
  // A. MATERI: ISI TEKS PROSEDUR
  { question: "Apa tujuan utama dari penulisan teks prosedur?", options: ["Menceritakan pengalaman masa lalu.", "Menjelaskan langkah-langkah melakukan sesuatu.", "Menggambarkan keindahan suatu tempat.", "Menyakinkan pembaca agar setuju dengan pendapat penulis."], answer: "Menjelaskan langkah-langkah melakukan sesuatu." },
  { question: "Mengapa teks prosedur harus bermakna dan dapat dipahami oleh orang lain?", options: ["Agar tulisan terlihat lebih panjang dan rumit.", "Agar pembaca dapat mengikuti instruksi tanpa kegagalan.", "Untuk menunjukkan tingkat kecerdasan penulis.", "Karena merupakan aturan wajib dari sekolah."], answer: "Agar pembaca dapat mengikuti instruksi tanpa kegagalan." },
  { question: "Jika kamu ingin membuat panduan 'Cara Mengaktifkan Handphone', informasi mana yang paling relevan untuk bagian isi?", options: ["Urutan menekan tombol daya hingga muncul layar utama.", "Sejarah penemuan telepon genggam di dunia.", "Daftar harga handphone terbaru tahun 2026.", "Manfaat handphone untuk bermain media sosial."], answer: "Urutan menekan tombol daya hingga muncul layar utama." },
  { question: "Perhatikan teks acak ini: (1) Angkat jemuran, (2) Jemur pakaian di bawah terik matahari, (3) Cuci pakaian hingga bersih. Urutan isi yang logis adalah...", options: ["1-2-3", "2-1-3", "3-2-1", "3-1-2"], answer: "3-2-1" },
  { question: "Mengapa membaca teks prosedur secara akurat dianggap penting sebelum mempraktikkan sesuatu di era media elektronik?", options: ["Agar baterai handphone tidak cepat habis.", "Karena teks prosedur lebih menarik daripada video.", "Untuk meminimalkan kegagalan dan kesalahan prosedur.", "Agar siswa mendapatkan nilai tinggi di leaderboard QUIZMAS."], answer: "Untuk meminimalkan kegagalan dan kesalahan prosedur." },
  { question: "Berdasarkan pengamatanmu, buatlah satu simpulan isi teks prosedur yang paling efektif untuk memotivasi siswa yang kurang berminat membaca!", options: ["Menyajikan instruksi singkat dengan poin-poin yang bermakna.", "Menggunakan bahasa ilmiah yang sangat teknis.", "Menuliskan langkah-langkah dalam bentuk paragraf panjang.", "Menghilangkan bagian alat dan bahan agar lebih praktis."], answer: "Menyajikan instruksi singkat dengan poin-poin yang bermakna." },

  // B. MATERI: STRUKTUR TEKS PROSEDUR
  { question: "Bagian teks prosedur yang berisi tujuan dan gambaran umum kegiatan disebut...", options: ["Tujuan", "Alat dan Bahan", "Langkah-langkah", "Penutup"], answer: "Tujuan" },
  { question: "Manakah urutan struktur teks prosedur yang paling tepat?", options: ["Langkah -> Bahan -> Tujuan -> Penutup", "Bahan -> Tujuan -> Penutup -> Langkah", "Tujuan -> Alat/Bahan -> Langkah -> Penutup", "Penutup -> Langkah -> Bahan -> Tujuan"], answer: "Tujuan -> Alat/Bahan -> Langkah -> Penutup" },
  { question: "Dalam teks 'Cara Membuat Mie Instan', bagian 'Siapkan satu bungkus mie, air 400cc, dan panci' masuk ke dalam struktur...", options: ["Tujuan", "Alat dan Bahan", "Langkah-langkah", "Simpulan"], answer: "Alat dan Bahan" },
  { question: "Sebuah teks prosedur tidak memiliki bagian 'Tujuan'. Apa analisis dampak yang paling mungkin terjadi pada pembaca?", options: ["Pembaca akan bingung mengenai apa hasil akhir dari kegiatan tersebut.", "Langkah-langkah kegiatan tetap mudah diikuti.", "Teks menjadi lebih ringkas dan menarik bagi siswa SMP.", "Ciri kebahasaan teks akan otomatis hilang."], answer: "Pembaca akan bingung mengenai apa hasil akhir dari kegiatan tersebut." },
  { question: "Jika sebuah teks prosedur memiliki langkah-langkah yang tidak berurutan, apakah teks tersebut masih bisa disebut teks prosedur yang baik?", options: ["Ya, karena yang penting isinya bermakna.", "Tidak, karena teks prosedur harus sistematis agar pekerjaan berjalan lancar.", "Ya, asalkan menggunakan media handphone.", "Tidak, karena melanggar aturan jurnal ilmiah."], answer: "Tidak, karena teks prosedur harus sistematis agar pekerjaan berjalan lancar." },
  { question: "Susunlah kerangka struktur teks prosedur yang utuh untuk judul 'Cara Menggunakan Aplikasi QUIZMAS'!", options: ["Tujuan (masuk kuis) -> Bahan (HP/Internet) -> Langkah (klik kode) -> Penutup (selesai).", "Bahan -> Langkah -> Penutup.", "Tujuan -> Langkah -> Bahan.", "Judul -> Penutup -> Langkah."], answer: "Tujuan (masuk kuis) -> Bahan (HP/Internet) -> Langkah (klik kode) -> Penutup (selesai)." },

  // C. MATERI: CIRI KEBAHASAAN
  { question: "Kata 'Tuangkan', 'Ambillah', dan 'Klik' merupakan contoh dari ciri kebahasaan...", options: ["Kalimat Imperatif (perintah)", "Kalimat Interogatif (tanya)", "Kalimat Deklaratif (pernyataan)", "Kalimat Majemuk"], answer: "Kalimat Imperatif (perintah)" },
  { question: "Kata-kata seperti 'kemudian', 'selanjutnya', dan 'setelah itu' berfungsi sebagai...", options: ["Penanda jumlah alat.", "Konjungsi temporal (urutan waktu).", "Kata ganti orang pertama.", "Penutup teks prosedur."], answer: "Konjungsi temporal (urutan waktu)." },
  { question: "Kalimat mana yang paling tepat menggunakan ciri kebahasaan teks prosedur?", options: ["Saya sedang memasak air di dapur.", "Rebuslah air hingga mendidih!", "Mengapa air harus direbus sampai mendidih?", "Air mendidih pada suhu 100 derajat."], answer: "Rebuslah air hingga mendidih!" },
  { question: "Bandingkan dua kalimat ini: (1) 'Potong bawang itu.' (2) 'Bawang dipotong oleh Ibu.' Kalimat yang merupakan ciri khas teks prosedur adalah...", options: ["Kalimat (1) karena bersifat perintah langsung.", "Kalimat (2) karena menjelaskan pelaku.", "Keduanya benar karena menggunakan kata kerja.", "Keduanya salah karena tidak ada kata sambung."], answer: "Kalimat (1) karena bersifat perintah langsung." },
  { question: "Mengapa penggunaan kalimat imperatif lebih efektif dalam teks prosedur daripada kalimat berita?", options: ["Agar teks terlihat lebih tegas dan galak.", "Untuk memberikan instruksi yang jelas dan langsung kepada pembaca.", "Karena kalimat berita terlalu pendek.", "Agar siswa lebih cepat menyelesaikan kuis di handphone."], answer: "Untuk memberikan instruksi yang jelas dan langsung kepada pembaca." },
  { question: "Rancanglah satu kalimat menggunakan konjungsi temporal dan kata kerja imperatif untuk langkah pertama mencuci tangan!", options: ["Pertama, basuhlah tanganmu dengan air yang mengalir.", "Tangan harus bersih sebelum makan.", "Mencuci tangan itu sangat penting.", "Setelah makan, saya mencuci tangan."], answer: "Pertama, basuhlah tanganmu dengan air yang mengalir." },

  // D. MATERI: KAIDAH PENULISAN (EBI)
  { question: "Manakah penulisan kata depan yang benar menurut kaidah EBI?", options: ["Diaduk", "Dikamar", "Di wadah", "Keatas"], answer: "Di wadah" },
  { question: "Apa fungsi tanda koma (,) dalam langkah-langkah teks prosedur yang menyebutkan beberapa bahan?", options: ["Sebagai tanda akhir kalimat.", "Untuk memisahkan unsur-unsur dalam suatu rincian.", "Agar pembaca bisa berhenti bernapas lama.", "Sebagai hiasan tulisan agar menarik."], answer: "Untuk memisahkan unsur-unsur dalam suatu rincian." },
  { question: "Pilihlah penulisan kalimat yang paling baku sesuai Ejaan Bahasa Indonesia!", options: ["masukan mie kedalam air mendidih.", "Masukkan mie ke dalam air mendidih!", "Masukkan mie ke dalam air mendidih. (Catatan: dalam teks formal tanpa seru berlebihan)", "Masukan mie kedalam air mendidih?"], answer: "Masukkan mie ke dalam air mendidih. (Catatan: dalam teks formal tanpa seru berlebihan)" },
  { question: "siapkan Gunting, lem, dan Kertas warna. Analisislah kesalahan penggunaan huruf kapital pada kalimat tersebut!", options: ["Kata 'siapkan', 'Gunting', dan 'Kertas' salah penggunaan kapitalnya.", "Hanya kata 'siapkan' yang salah karena di awal kalimat.", "Penulisan tersebut sudah benar menurut kaidah terbaru.", "Semua kata harus menggunakan huruf kapital semua."], answer: "Kata 'siapkan', 'Gunting', dan 'Kertas' salah penggunaan kapitalnya." },
  { question: "Validasilah kalimat berikut: 'Silahkan ambil nomor antrian di loket.' Apakah sudah sesuai dengan KBBI/EBI?", options: ["Benar, karena kata 'silahkan' sudah umum digunakan.", "Salah, yang benar adalah 'silakan' tanpa huruf 'h'.", "Salah, seharusnya 'antrian' ditulis 'antre'.", "Benar, karena digunakan dalam teks prosedur resmi."], answer: "Salah, yang benar adalah 'silakan' tanpa huruf 'h'." },
  { question: "Perbaikilah kalimat ini menjadi kaidah penulisan yang sempurna: 'rebus air dipanci sampai mendidih'", options: ["Rebuslah air di panci sampai mendidih.", "Rebus air di panci sampai mendidih?", "rebus air dipanci Sampai Mendidih.", "Rebus air Di panci sampai mendidih!"], answer: "Rebuslah air di panci sampai mendidih." }
];